item{

    id: 1
    name: 'bed'

}
item{

    id: 2
    name: 'chair'

}
item{

    id: 3
    name: 'couch'

}
item{

    id: 4
    name: 'dining_table'

}
item{

    id: 5
    name: 'potted_plant'

}
item{

    id: 6
    name: 'toilet'

}
